export const assetTypeIcon: any = {
  vm: 'tencentcloud:cvm',
  mysql: 'tencentcloud:mysql',
  kubernetes: 'tencentcloud:tke',
  redis: 'tencentcloud:redis',
  tcaplus: 'tencentcloud:tcaplusdatabase',
  mongo: 'tencentcloud:mongodb',
  postgresql: 'tencentcloud:postgresql',
  vpc: 'tencentcloud:vpc',
  sub_vpc: 'tencentcloud:subnet',
  dcx: 'tencentcloud:dc',
  lb: 'tencentcloud:clb',
  dns: 'tencentcloud:dns',
  cdn: 'tencentcloud:cdn',
  ssl: 'tencentcloud:ssl',
  cos: 'tencentcloud:cos',
  cfs: 'tencentcloud:cfs',
  cbs: 'tencentcloud:cbs',
  kafka: 'tencentcloud:kafka',
  es: 'tencentcloud:es',
  iam: 'tencentcloud:iam',
  region: 'tencentcloud:region'
}

export const vendorIcon: any = {
  tencent: 'tencentcloud:tencentcloud',
  gcp: 'logos:google-cloud',
  aws: 'logos:aws',
  azure: 'logos:microsoft-azure',
  huawei: 'tencentcloud:huawei',
  zenlayer: 'tencentcloud:zenlayer',
  other: ''
}

export const countryIcon: any = {
  TH: 'twemoji:flag-thailand',
  CH: 'twemoji:flag-china',
  HK: 'twemoji:flag-hong-kong-sar-china',
  TW: 'twemoji:flag-for-flag-taiwan',
  IN: 'twemoji:flag-for-flag-india',
  SG: 'twemoji:flag-singapore',
  JP: 'twemoji:flag-japan',
  DE: 'twemoji:flag-germany',
  RU: 'twemoji:flag-russia',
  US: 'twemoji:flag-united-states',
  CA: 'twemoji:flag-canada',
  GB: 'twemoji:flag-united-kingdom',
  BR: 'twemoji:flag-brazil',
  ID: 'twemoji:flag-indonesia',
  SE: 'twemoji:flag-sweden',
  ZA: 'twemoji:flag-south-africa',
  FR: 'twemoji:flag-france',
  IE: 'twemoji:flag-ireland',
  KR: 'twemoji:flag-south-korea',
  AU: 'twemoji:flag-australia',
  BH: 'twemoji:flag-bahrain',
  NL: 'twemoji:flag-netherlands',
  Europe: 'twemoji:flag-european-union',
  Logical: 'carbon:logical-partition',
  Asia: 'twemoji:globe-showing-asia-australia',
  Africa: 'twemoji:globe-showing-europe-africa',
  'Middle East': 'twemoji:flag-united-arab-emirates',
  'South America': 'ic:outline-south-america'
}
